### ISSUE TITLE
Did not work for me...

### ISSUE THREAD

**Issue by peanut-buttermilk** [tecton/Leetcode-Submission-Downloader#1]
xxx$ /usr/local/bin/python /tmp/lcd/Leetcode-Submission-Downloader/leetcodeDownloader.py xxx@gmail.com
Password:
Check page 1
/usr/local/lib/python2.7/site-packages/bs4/**init**.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Check page 2
Check page 3
Check page 4
Check page 5
Check page 6
Check page 7
Check page 8
Check page 9
Check page 10
Check page 11
Check page 12
Check page 13
Check page 14
Check page 15
Check page 16
Check page 17
Check page 18
Check page 19
Check page 20
Check page 21
Check page 22
Check page 23
Check page 24
Check page 25
Check page 26
Check page 27
Check page 28
Check page 29
Check page 30
Check page 31
Check page 32
Check page 33
Check page 34
Check page 35
Check page 36
Check page 37
Check page 38
Check page 39
Check page 40
Check page 41
Check page 42
Check page 43
Check page 44
Check page 45
All submissions checked.
xxx$ find .
.
./code

**Comment by tecton** [comment]
@peanut-buttermilk regex updated. It should work now, thanks.

**Comment by peanut-buttermilk** [comment]
Thanks a ton... working now.
